# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "AntonioMeireles/ClearLinux"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    usermod -aG docker clear
    swupd bundle-add cloud-native-basic
    mkdir /etc/sysctl.d
    echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/60-k8s.conf
    systemctl restart systemd-sysctl.service
    #systemctl enable crio.service
    systemctl enable kubelet.service
    systemctl mask $(sed -n -e 's#^/dev/\([0-9a-z]*\).*#dev-\1.swap#p' /proc/swaps) 2>/dev/null
    swapoff -a
    echo "127.0.0.1 localhost `hostname`" > /etc/hosts
    mkdir /etc/systemd/system/docker.service.d/
    echo '[Service]\nEnvironment="DOCKER_DEFAULT_RUNTIME=--default-runtime runc"' > /etc/systemd/system/docker.service.d/51-runtime.conf
    mkdir /etc/systemd/system/kubelet.service.d/
    echo '[Service]\nEnvironment="KUBELET_EXTRA_ARGS="' > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

    systemctl daemon-reload
    systemctl restart docker
    systemctl restart kubelet
    
    #systemctl start crio
    systemctl start kubelet
    systemctl daemon-reload
    systemctl restart docker
    #systemctl restart crio
    systemctl restart kubelet
  SHELL
end
